services:
  _defaults:
    public: true

  bit_bag.sylius_mollie_plugin.event_listener.shipment_ship_event_listener:
    class: BitBag\SyliusMolliePlugin\EventListener\ShipmentShipEventListener
    tags:
      - { name: kernel.event_listener, event: sylius.shipment.post_ship,  method: shipToMollie }
    arguments:
      ['@bitbag_sylius_mollie_plugin.mollie_api_client']
