services:
    bitbag_sylius_mollie_plugin.gateway_factory.mollie:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        public: true
        arguments:
            -  BitBag\SyliusMolliePlugin\MollieGatewayFactory
        tags:
            - { name: payum.gateway_factory_builder, factory: mollie }

    bitbag_sylius_mollie_plugin.gateway_factory.mollie_subscription:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        public: true
        arguments:
            -  BitBag\SyliusMolliePlugin\MollieSubscriptionGatewayFactory
        tags:
            - { name: payum.gateway_factory_builder, factory: mollie_subscription }
