services:
  _defaults:
    public: true

  bitbag_sylius_mollie_plugin.payment_surcharge.types.fix_amount:
    class: BitBag\SyliusMolliePlugin\PaymentFee\Types\FixedAmount
    arguments:
      - "@sylius.factory.adjustment"

  bitbag_sylius_mollie_plugin.payment_surcharge.types.fix_amount_and_percentage:
    class: BitBag\SyliusMolliePlugin\PaymentFee\Types\FixedAmountAndPercentage
    arguments:
      - "@sylius.factory.adjustment"
      - '@bitbag_sylius_mollie_plugin.payment_surcharge.types.percentage'
      - '@bitbag_sylius_mollie_plugin.payment_surcharge.types.fix_amount'

  bitbag_sylius_mollie_plugin.payment_surcharge.types.percentage:
    class: BitBag\SyliusMolliePlugin\PaymentFee\Types\Percentage
    arguments:
      - "@sylius.factory.adjustment"

  bitbag_sylius_mollie_plugin.payment_surcharge.calculate:
    class: BitBag\SyliusMolliePlugin\PaymentFee\Calculate
    arguments:
      - "@bitbag_sylius_mollie_plugin.payment_surcharge.types.fix_amount"
      - "@bitbag_sylius_mollie_plugin.payment_surcharge.types.percentage"
      - "@bitbag_sylius_mollie_plugin.payment_surcharge.types.fix_amount_and_percentage"
