services:
    bitbag_sylius_mollie_plugin.payment_processing.cancel_recurring_subscription:
        class: BitBag\SyliusMolliePlugin\PaymentProcessing\CancelRecurringSubscriptionProcessor
        public: true
        arguments:
            - "@payum"
            - "@session"
