services:
  _defaults:
    public: true

  bitbag_sylius_mollie_plugin.resolver.payment_methods:
    class: BitBag\SyliusMolliePlugin\Resolver\MolliePaymentsMethodResolver
    arguments:
      - "@sylius.context.cart"
      - "@sylius.repository.gateway_config"
      - "@bitbag_sylius_mollie_plugin.resolver.payment_methods_image"
      - "@bitbag_sylius_mollie_plugin.repository.mollie_gateway_config"

  bitbag_sylius_mollie_plugin.resolver.payment_methods_image:
    class: BitBag\SyliusMolliePlugin\Resolver\MolliePaymentMethodImageResolver
    arguments:
      - "%images_dir%"

  bitbag_sylius_mollie_plugin.resolver.payment_config:
    class: BitBag\SyliusMolliePlugin\Resolver\PaymentMethodConfigResolver
    arguments:
      - "@bitbag_sylius_mollie_plugin.repository.mollie_gateway_config"

  bitbag_sylius_mollie_plugin.resolver.tax_unit_item:
    class: BitBag\SyliusMolliePlugin\Resolver\TaxUnitItemResolver
    arguments:
      - '@sylius.provider.channel_based_default_zone_provider'
      - '@sylius.zone_matcher'
      - '@sylius.tax_rate_resolver'

  bitbag_sylius_mollie_plugin.resolver.tax_shipment:
    class: BitBag\SyliusMolliePlugin\Resolver\TaxShipmentResolver
    arguments:
      - '@sylius.provider.channel_based_default_zone_provider'
      - '@sylius.zone_matcher'
      - '@sylius.tax_rate_resolver'
