services:
  _defaults:
    public: true

  bitbag_sylius_mollie_plugin.resolver.payment_methods:
    class: BitBag\SyliusMolliePlugin\Resolver\MolliePaymentsMethodResolver
    arguments:
      - "@sylius.context.cart"
      - "@sylius.repository.gateway_config"
      - "@bitbag_sylius_mollie_plugin.resolver.payment_methods_image"
      - "@bitbag_sylius_mollie_plugin.repository.mollie_gateway_config"

  bitbag_sylius_mollie_plugin.resolver.payment_methods_image:
    class: BitBag\SyliusMolliePlugin\Resolver\MolliePaymentMethodImageResolver
    arguments:
      - "%images_dir%"
