imports:
    - { resource: "services/form.xml" }
    - { resource: "services/gateway_factory.xml" }
    - { resource: "services/action.xml" }
    - { resource: "services/validators.xml" }
    - { resource: "services/controller.xml" }
    - { resource: "services/payment_processing.xml" }
    - { resource: "services/event_listener.xml" }
    - { resource: "services/helper.xml" }
    - { resource: "services/calculator.xml" }
    - { resource: "services/methods.xml" }
    - { resource: "services/factory.xml" }
    - { resource: "services/payment_fee.xml" }
    - { resource: "services/processor/payment_fee.xml" }
    - { resource: "services/uploader/payment_method_logo_uploader.xml" }
    - { resource: "services/resolver.xml" }

services:
    _defaults:
        public: true

    bitbag_sylius_mollie_plugin.mollie_api_client:
        class: BitBag\SyliusMolliePlugin\Client\MollieApiClient

    bitbag_sylius_mollie_plugin.get_http_request:
        class: Payum\Core\Request\GetHttpRequest
