bitbag_sylius_mollie_plugin_cancel_subscription_mollie:
  path: /account/order/{orderId}/subscription-mollie/cancel
  methods: [PUT]
  defaults:
    _controller: bitbag_sylius_mollie_plugin.controller.subscription:applyStateMachineTransitionAction
    _sylius:
      repository:
        method: findOneByOrderId
        arguments:
          - $orderId
      state_machine:
        graph: mollie_subscription
        transition: cancel
      redirect: referer
      flash: bitbag_sylius_mollie_plugin.subscription.cancelled
