sylius_grid:
  templates:
    action:
      cancel_subscription_mollie: "@BitBagSyliusMolliePlugin/Shop/Grid/Action/cancelSubscriptionMollie.html.twig"
  grids:
    sylius_shop_account_order:
      actions:
        item:
          cancel_subscription_mollie:
            type: cancel_subscription_mollie
            label: bitbag_sylius_mollie_plugin.ui.cancel_subscription
            options:
              link:
                route: bitbag_sylius_mollie_plugin_cancel_subscription_mollie
                parameters:
                  orderId: resource.id
