sylius_resource:
  resources:
    bitbag_sylius_mollie_plugin.template_mollie_email:
      driver: doctrine/orm
      classes:
        model: BitBag\SyliusMolliePlugin\Entity\TemplateMollieEmail
        form: BitBag\SyliusMolliePlugin\Form\Type\TemplateMollieEmailType
