winzou_state_machine:
  sylius_order_checkout:
    transitions:
      complete:
        from: [payment_selected, payment_skipped, addressed, shipping_skipped, payment_selected, cart]
        to: completed
    callbacks:
      after:
        bitbag_sylius_mollie_plugin_payment_surcharge:
          on: ["select_payment"]
          do: ["@bitbag_sylius_mollie_plugin.processor.payment_surcharge_processor", "process"]
          args: ["object"]
  sylius_shipment:
    transitions:
      create_and_ship:
        from: [cart]
        to: shipped
    callbacks:
      before:
        bitbag_purify_empty_ready_shipments:
          on: ["ship", "create_and_ship"]
          do: ["@bitbag_sylius_mollie_plugin.purifier.partial_ship.order_shipment_purifier", "purify"]
          args: ["object.getOrder()"]
      after:
        sylius_resolve_state:
          on: ["ship", "create_and_ship"]
          do: ["@sylius.state_resolver.order_shipping", "resolve"]
          args: ["object.getOrder()"]
