sylius_grid:
  grids:
    bitbag_sylius_mollie_plugin_mollie_logger:
      driver:
        name: doctrine/orm
        options:
          class: BitBag\SyliusMolliePlugin\Entity\MollieLogger
      fields:
        level:
          type: string
          label: sylius.ui.name
        errorCode:
          type: string
          label: sylius.ui.description
        message:
          type: string
          label: sylius.ui.enabled
        dateTime:
          type: datetime
          label: sylius.ui.enabled
          options:
            format: 'Y:m:d H:i:s'
        objectType:
          type: string
          label: sylius.ui.enabled
