sylius_mailer:
  emails:
    payment_link:
      subject: bitbag_sylius_mollie_plugin.emails.payment_link.subject
      template: "@BitBagSyliusMolliePlugin/Admin/Email/paymentLinkConfirmation.html.twig"
