bitbag_sylius_mollie_plugin_mollie_logger:
  resource: |
    alias: bitbag_sylius_mollie_plugin.template_mollie_email
    section: admin
    path: /mollie/email-template
    templates: SyliusAdminBundle:Crud
    redirect: update
    grid: bitbag_sylius_mollie_plugin_template_mollie_email
    vars:
        all:
            subheader: bitbag_sylius_mollie_plugin.ui.mollie_email_template
        index:
            icon: 'email'
  type: sylius.resource
